name: Build

on: 
  push:
    paths-ignore: &paths_ignore
      - 'docs/**'
      - 'share/**'
      - 'utils/cmake/**'
      - 'utils/config/**'
      - 'utils/valgrind/**'
      - '**.txt'
      - '**.md'
  pull_request:
    paths-ignore: *paths_ignore

concurrency:
  # De-duplicate concurrent workflow runs on the same branch/ref
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop' }}

jobs:
  build:
    name: ${{ matrix.compiler }}-${{ matrix.version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-26, macos-26-intel ]
        compiler: [ gcc ]
        version: [ 12, 13, 14, 15 ]
        extra_flags: [ -g ]

        include:
          - os: ubuntu-22.04
            compiler: gcc
            version: 12 # no package available for gcc 13+

          # --- LLVM clang coverage ---

          - os: macos-26
            compiler: clang
            version: 22
          - os: macos-26-intel
            compiler: clang
            version: 22


    container:
      image: ${{ matrix.container }}

    env:
      COMPILER_VERSION: ${{ matrix.version }}
      CC: ${{ matrix.compiler }}
      CFLAGS: ${{ matrix.extra_flags }}
      CONFIGURE_ARGS: --disable-mpi-compat --enable-rpath
      GASNET_BACKTRACE: 1
      GASNET_SPAWN_VERBOSE: 1
      GASNET_SPAWNFN: L
      GASNET_MASTERIP: 127.0.0.1

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install Ubuntu Native Dependencies
      if: ${{ contains(matrix.os, 'ubuntu') && matrix.container == '' && matrix.compiler == 'gcc' }}
      run: |
        set -x
        sudo apt update
        #sudo apt list -a 'gcc-*'
        sudo apt install -y build-essential
        if (( ${COMPILER_VERSION} < 15 )) ; then \
          sudo apt install -y gcc-${COMPILER_VERSION} ; \
        else \
          curl -L https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh -o install-homebrew.sh ; \
          chmod +x install-homebrew.sh ; \
          env CI=1 ./install-homebrew.sh ; \
          HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew" ; \
          ${HOMEBREW_PREFIX}/bin/brew install -v gcc@${COMPILER_VERSION} binutils ; \
          ls -al ${HOMEBREW_PREFIX}/bin ; \
          echo "PATH=${HOMEBREW_PREFIX}/bin:${PATH}" >> "$GITHUB_ENV" ; \
          : Homebrew GCC@15 needs binutils 2.44+ ; \
          HOMEBREW_BINUTILS=$(ls -d ${HOMEBREW_PREFIX}/Cellar/binutils/2.*/bin ) ; \
          ls -al ${HOMEBREW_BINUTILS} ; \
          echo "FFLAGS=$FFLAGS -B ${HOMEBREW_BINUTILS}" >> "$GITHUB_ENV" ; \
          echo "CFLAGS=$CFLAGS -B ${HOMEBREW_BINUTILS}" >> "$GITHUB_ENV" ; \
          echo "CXXFLAGS=$CXXFLAGS -B ${HOMEBREW_BINUTILS}" >> "$GITHUB_ENV" ; \
        fi

    - name: Install Ubuntu Container Dependencies
      if: ${{ contains(matrix.os, 'ubuntu') && matrix.container != '' && !contains(matrix.container, 'phhargrove') }}
      run: |
        set -x
        apt update
        apt install -y build-essential # pkg-config make git curl

    - name: Install macOS Dependencies
      if: contains(matrix.os, 'macos') && matrix.version == '12'
      run: |
        set -x
        brew update
        brew install gcc@12

    - name: Install LLVM on macOS
      if: contains(matrix.os, 'macos') && matrix.compiler == 'clang'
      run: |
        set -x
        brew install llvm@${COMPILER_VERSION} 
        # Prepend homebrew clang to PATH:
        echo "PATH=$(brew --prefix)/opt/llvm/bin:${PATH}" >> "$GITHUB_ENV"

    - name: Setup Compilers
      run: |
        set -x
        if test "$CC" = "clang" ; then
          echo "CXX=clang++" >> "$GITHUB_ENV"
        elif test "$CC" = "icx" ; then 
          echo "CXX=icpx" >> "$GITHUB_ENV"
        else 
          echo "CC=gcc-${COMPILER_VERSION}" >> "$GITHUB_ENV"
          echo "CXX=g++-${COMPILER_VERSION}" >> "$GITHUB_ENV"
          # XCode 26 / gcc bug workaround: 
          # <mach/mach_time.h> and <mach/mach.h> generate xnu_static_assert_struct_size errors from <mach/message.h>
          if [[ ${{ matrix.os }} =~ macos-26 ]] ; then
            #echo "CONFIGURE_ARGS=$CONFIGURE_ARGS --enable-force-posix-realtime --disable-ccs-rpc" >> "$GITHUB_ENV"
            echo "CONFIGURE_ARGS=$CONFIGURE_ARGS --enable-force-posix-realtime" >> "$GITHUB_ENV"
          fi
        fi

    - name: Version info
      run: |
        echo == TOOL VERSIONS ==
        echo Platform version info:
        uname -a
        if test -r /etc/os-release ; then grep -e NAME -e VERSION /etc/os-release  ; fi
        if test -x /usr/bin/sw_vers ; then /usr/bin/sw_vers ; fi
        echo
        echo PATH="$PATH"
        for tool in ${CC} ${CXX} make ; do
          ( echo ; set -x ; w=$(which $tool) ; ls -al $w ; ls -alhL $w ; $tool --version )
        done

    - name: configure
      run: |
        set -x
        ./configure --prefix=$PWD/inst ${CONFIGURE_ARGS}

    - name: make all
      run: |
        set -x
        make all

    - name: make install
      run: |
        set -x
        make install

    - name: make test_install
      run: |
        set -x
        make test_install

    - name: make check
      run: |
        set -x
        make check


